### ISSUE TITLE
Invert color scheme

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_MHCC#1]
_From @brashrebel on February 18, 2016 18:6_

Client has requested a significant change in the color scheme. I think the staging site might be a good place for this. You'll have to push prod to staging. Then we need the site's background color to be white and text changed to black (or dark gray) with the dark purple for headings. We'll likely have to iterate a little bit on this.

_Copied from original issue: realbig/RBMC_TH_MMHC#2_

**Comment by brashrebel** [comment]
Actually, the client has now requested that the "coffee" admin color scheme be used for the site frontend.

**Comment by d4mation** [comment]
I have it now set up on Staging to use a variation of the Coffee Admin Theme for its coloration.

http://mounthopecommunitychurch-com.realbig.staging.wpengine.com/ 

I've narrowed it down to 7 different colors that need to be set in the Sass, so I'm going to move those over to the Customizer while finishing up #3.

**Comment by d4mation** [comment]
I've got the changes up on Staging. The colors are able to be changed via the Customizer, but it defaults to using the colors I pulled from the Coffee Admin Theme.

![image](https://cloud.githubusercontent.com/assets/7770631/13577579/0f431de0-e461-11e5-874d-2372e8a20b01.png)

**Comment by d4mation** [comment]
This is now Live, along with #2!

The Queries for Events are based of the new Post Meta, so there's no need to Schedule Posts anymore.
